### ISSUE TITLE
Some errors and compiler warning when compiling FPCamera.c with gcc (not g++)

### ISSUE THREAD

**Issue by zzador** [JeffM2501/raylibExtras#1]
Compiling FPCamera.c with gcc produces the following output (with -wall):

src/utils/FPCamera.c: In function 'InitFPCamera':
src/utils/FPCamera.c:37:16: error: 'NULL' undeclared (first use in this function)
  if (camera == NULL)
                ^~~~
src/utils/FPCamera.c:37:16: note: 'NULL' is defined in header '<stddef.h>'; did you forget to '#include <stddef.h>'?
src/utils/FPCamera.c:33:1:
+#include <stddef.h>
 #include <math.h>
src/utils/FPCamera.c:37:16:
  if (camera == NULL)
                ^~~~
src/utils/FPCamera.c:37:16: note: each undeclared identifier is reported only once for each function it appears in
src/utils/FPCamera.c:53:22: error: expected expression before '{' token
  camera->MoveSpeed = { 1,1,1 };
                      ^
src/utils/FPCamera.c:54:22: error: expected expression before '{' token
  camera->TurnSpeed = { 90,90 };
                      ^
src/utils/FPCamera.c:72:23: error: expected expression before '{' token
  camera->ViewAngles = { 0,0 };
                       ^
src/utils/FPCamera.c:79:70: error: expected expression before 'Vector3'
  camera->ViewCamera.target = Vector3Add(camera->ViewCamera.position, Vector3{ 0, 0, camera->TargetDistance });
                                                                      ^~~~~~~
src/utils/FPCamera.c:80:26: error: expected expression before '{' token
  camera->ViewCamera.up = { 0.0f, 1.0f, 0.0f };
                          ^
src/utils/FPCamera.c: In function 'ResizeFPCameraView':
src/utils/FPCamera.c:103:16: error: 'NULL' undeclared (first use in this function)
  if (camera == NULL)
                ^~~~
src/utils/FPCamera.c:103:16: note: 'NULL' is defined in header '<stddef.h>'; did you forget to '#include <stddef.h>'?
src/utils/FPCamera.c: In function 'GetSpeedForAxis':
src/utils/FPCamera.c:122:16: error: 'NULL' undeclared (first use in this function)
  if (camera == NULL)
                ^~~~
src/utils/FPCamera.c:122:16: note: 'NULL' is defined in header '<stddef.h>'; did you forget to '#include <stddef.h>'?
src/utils/FPCamera.c: In function 'UpdateFPCamera':
src/utils/FPCamera.c:141:16: error: 'NULL' undeclared (first use in this function)
  if (camera == NULL)
                ^~~~
src/utils/FPCamera.c:141:16: note: 'NULL' is defined in header '<stddef.h>'; did you forget to '#include <stddef.h>'?
src/utils/FPCamera.c:180:15: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
  Vector3 right{ forward.z * -1.0f, 0, forward.x };
               ^
src/utils/FPCamera.c:180:34: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  Vector3 right{ forward.z * -1.0f, 0, forward.x };
                                  ^
src/utils/FPCamera.c:180:37: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  Vector3 right{ forward.z * -1.0f, 0, forward.x };
                                     ^
src/utils/FPCamera.c:180:37: warning: statement with no effect [-Wunused-value]
src/utils/FPCamera.c:180:48: error: expected ';' before '}' token
  Vector3 right{ forward.z * -1.0f, 0, forward.x };
                                                ^~
                                                ;
src/utils/FPCamera.c:185:75: error: 'right' undeclared (first use in this function); did you mean 'rint'?
  camera->CameraPosition = Vector3Add(camera->CameraPosition, Vector3Scale(right, direction[MOVE_RIGHT] - direction[MOVE_LEFT]));
                                                                           ^~~~~
                                                                           rint
src/utils/FPCamera.c:212:36: error: expected expression before 'Vector3'
  Matrix rotation = MatrixRotateXYZ(Vector3{ PI * 2 - camera->ViewAngles.y, PI * 2 - camera->ViewAngles.x, 0 });
                                    ^~~~~~~
src/utils/FPCamera.c:225:3: error: 'constexpr' undeclared (first use in this function)
   constexpr float viewBobbleDampen = 8.0f;
   ^~~~~~~~~
src/utils/FPCamera.c:225:12: error: expected ';' before 'float'
   constexpr float viewBobbleDampen = 8.0f;
            ^~~~~~
            ;
src/utils/FPCamera.c:227:44: error: 'viewBobbleDampen' undeclared (first use in this function)
   eyeOfset -= sinf(camera->CurrentBobble / viewBobbleDampen) * camera->ViewBobbleMagnatude;
                                            ^~~~~~~~~~~~~~~~
src/utils/FPCamera.c:182:10: warning: unused variable 'oldPostion' [-Wunused-variable]
  Vector3 oldPostion = camera->CameraPosition;
          ^~~~~~~~~~
src/utils/FPCamera.c:161:8: warning: unused variable 'mouseWheelMove' [-Wunused-variable]
  float mouseWheelMove = GetMouseWheelMove();
        ^~~~~~~~~~~~~~

**Comment by JeffM2501** [comment]
I've pushed some commits that should take care of these issues, please let me know if they work or if there are other issues.

**Comment by zzador** [comment]
Yes...all compile errors resolved. Only one warning left:

src/utils/FPCamera.c:161:8: warning: unused variable 'mouseWheelMove' [-Wunused-variable]
float mouseWheelMove = GetMouseWheelMove();

**Comment by JeffM2501** [comment]
Should be fixed now

**Comment by zzador** [comment]
GCC compiles now without errors and warnings.
