### ISSUE TITLE
rlImGui works on Linux, blank on Mac

### ISSUE THREAD

**Issue by bart9h** [JeffM2501/raylibExtras#11]
I managed to get a hello world raylib+imgui program working on Linux.

When I got to the Mac, it compiled without errors, but when running it failed to render the imgui part.
Rendering with raylib works. And I know the imgui part is working, because I blindly clicked around where the button was supposed to be, and eventually it reacted (a print on stdout).

I'm new to both imgui and raylib, can you help me debug this one?

**Comment by cpowell** [comment]
I'm experiencing the same issue as OP. I have a little test rlImGui app that works fine on Windows but demonstrates the blank behavior mentioned above.

**Comment by JeffM2501** [comment]
Yeah this is the old rlImgui, it's not maintained anymore and hasn't ever worked for mac. You want the real one here
https://github.com/raylib-extras/rlImGui

I will remove this rlImGui, it should not be used.
